title: "Resource Manager Demo Stack"
stackDescription: "A stack to demonstrate how to use Resource Manager in the Oracle Cloud."
schemaVersion: 1.1.0
version: "20210809"
locale: “en"

variableGroups:
    - title: "Required Inputs"
      variables:
      - "compartment_ocid"
      - "region"

variables:
      "compartment_ocid":
        type: oci:identity:compartment:id
        visible: true
        required: true
        title: "Compartment"
        description: "The compartment to create the resources in."

      "region":
        type: oci:identity:region:name
        visible: true
        required: true
        title: "Region"
        description: "The region in which to create resources."
        
      
        
